#! /bin/sh

# Restore wallpaper
bash $HOME/.config/bspwm/.fehbg

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/polybar/launch.sh

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6' '7' '8' '9'
		let name++
	done
}
workspaces

bspc config border_width         1
bspc config window_gap           15
bspc config split_ratio          0.50
bspc config border_radius        5

bspc config focused_border_color      "#7aa2f7"
bspc config normal_border_color       "#32344a"
bspc config active_border_color       "#444b6a"
bspc config presel_feedback_color     "#7aa2f7"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst ksuperkey

# Launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# polkit agent
if [[! 'pidof xfce-polkit']]; then
  /usr/lib/xfce-polkit/xfce-polkit &
fi

# Launch keybindings daemon
sxhkd &

# Start udiskie
udiskie &

dex -a -s ~/.config/autostart/

# start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/bspwm/picom.conf &

# fix Java GUI rendering - found in baskerville's dotfiles
IRONIC_WM_NAME="LG3D"
NET_WIN=$(xprop -root _NET_SUPPORTING_WM_CHECK | awk -F "# " '{print $2}')
if [[ "$NET_WIN" == 0x* ]]; then
    xprop -id "$NET_WIN" -remove _NET_WM_NAME
    xprop -id "$NET_WIN" -f _NET_WM_NAME 8s -set _NET_WM_NAME "$IRONIC_WM_NAME"
else
    xprop -root -remove _NET_WM_NAME
    xprop -root -f _NET_WM_NAME 8s -set _NET_WM_NAME "$IRONIC_WM_NAME"
fi

export _JAVA_AWR_WM_NONREPARENTING=1
export _JAVA_AWT_WM_NONREPARENTING=1
