[display]
separator = ": "
ascii_path = "~/.config/swiftfetch/ascii.txt"
ascii_color = "blue"

[colors]
# {#replace_color(data.colors.base0B)#}
green = "#76946a"
# {#replace_color(data.colors.base0D)#}
blue = "#7e9cd8"
# {#replace_color(data.colors.base0F)#}
magenta = "#d27e99"
# {#replace_color(data.colors.base0A)#}
yellow = "#c0a36e"
# {#replace_color(data.colors.base08)#}
red = "#c34043"
# {#replace_color(data.colors.base0C)#}
cyan = "#6a9589"

[[display.items]]
key = "user_info"
type = "default"
value = "user_info"

[[display.items]]
key = ""
type = "text"
value = "┌────────────────── System Information ───────────────────┐"
color = "yellow"

[[display.items]]
key = "           󰣇 ‣ os"
type = "default"
value = "os"
color = "cyan"
value_color = "blue"

[[display.items]]
key = "           󰍛 ‣ kernel"
type = "default"
value = "kernel"
color = "cyan"
value_color = "magenta"

[[display.items]]
key = "            ‣ wm"
type = "default"
value = "wm"
color = "cyan"
value_color = "green"

[[display.items]]
key = "            ‣ editor"
type = "default"
value = "editor"
color = "cyan"
value_color = "green"

[[display.items]]
key = "            ‣ shell"
type = "default"
value = "shell"
color = "cyan"
value_color = "red"

[[display.items]]
key = "            ‣ term"
type = "default"
value = "terminal"
color = "cyan"
value_color = "red"

[[display.items]]
key = "            ‣ pkgs"
type = "default"
value = "pkg_count"
color = "cyan"
value_color = "blue"

[[display.items]]
key = "            ‣ flat"
type = "default"
value = "flatpak_pkg_count"
color = "cyan"
value_color = "blue"

[[display.items]]
key = ""
type = "text"
value = "├───────────────── Hardware Information ─────────────────┤"
color = "yellow"

[[display.items]]
key = "           󰍛 ‣ cpu"
type = "default"
value = "cpu"
color = "cyan"
value_color = "red"

[[display.items]]
key = "           󰓅 ‣ ram"
type = "default"
value = "memory"
color = "cyan"
value_color = "green"

# [[display.items]]
# key = ""
# type = "text"
# value = "├───────────────── Uptime Information ───────────────────┤"
# color = "yellow"
#
# [[display.items]]
# key = "            ‣ uptime"
# type = "default"
# value = "uptime_seconds"
# color = "yellow"
#
# [[display.items]]
# key = "            ‣ age"
# type = "default"
# value = "os_age"
# color = "yellow"

[[display.items]]
key = ""
type = "text"
value = "└────────────────────────────────────────────────────────┘"
color = "yellow"

[[display.ascii]]
type = "ascii"
path = "~/.config/swiftfetch/ascii.txt"
color = "green"
